version: '2'
services:

  w4u-glue:
    image: tamboraorg/creglue:0.2020
    container_name: w4uglue
    volumes:
     - /var/run/docker.sock:/tmp/docker.sock:ro

  w4u-vue:
    image: tamboraorg/credevvue:0.2020
    container_name: w4uvue
    volumes:
     - ./vue-components:/cre/vue-components
     - ./web-components:/cre/web-components
     - ./npm-components:/cre/npm-components  
    volumes_from:
     - w4u-glue

# docker-compose --file dc-prepare.yml up -d

     
